apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-demo
  labels:
    app: apache-demo
spec:
  selector:
    matchLabels:
      app: apache-demo
  template:
    metadata:
      labels:
        app: apache-demo
    spec:
      initContainers:
      - env:
        - name: SECRET_secret1
          valueFrom:
            secretKeyRef:
              name: apache-demo
              key: secret1
        - name: SECRET_secret2
          valueFrom:
            secretKeyRef:
              name: apache-demo
              key: secret2
        image: ghcr.io/spreadshirt/k8s-multi-secret-to-file:latest
        imagePullPolicy: Always
        name: secret-init
        volumeMounts:
          - mountPath: /etc/rendered
            name: init-share
          - mountPath: /etc/templates/path/to/secret/config
            name: configmap
            subPath: secret-config
      containers:
        - name: apache
          image: php:8-apache
          ports:
            - containerPort: 80
          volumeMounts:
          - mountPath: /path/to/secret/config
            name: init-share
            subPath: path/to/secret/config
      volumes:
        - emptyDir: { }
          name: init-share
        - configMap:
            name: apache-demo-cfg
          name: configmap